FROM node:20-alpine

RUN apk add --no-cache libc6-compat

COPY . /app

WORKDIR /app

RUN npm install -g pnpm@8.11.0
RUN pnpm install

ARG NEXT_PUBLIC_API_MOCKING \ 
NEXT_PUBLIC_SITE_URL \ 
NEXT_PUBLIC_SERVER \ 
NEXT_PUBLIC_WS \ 
NEXT_PUBLIC_CRYPTO_IV_SECRET \ 
NEXT_PUBLIC_CRYPTO_IV_LENGTH \
SENTRY_AUTH_TOKEN \
NEXT_PUBLIC_KAKAO_MAP \
NEXT_PUBLIC_GA_ACTIVE \
NEXT_PUBLIC_GA_ID \
NEXT_PUBLIC_SENTRY_DSN \
NEXT_PUBLIC_SENTRY_ACTIVE \
NEXT_PUBLIC_GOOGLE_VERIFICATION \
NEXT_PUBLIC_NAVER_VERIFICATION \
NEXT_PUBLIC_SSE \
NEXT_PUBLIC_FIREBASE_API_KEY \
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
NEXT_PUBLIC_FIREBASE_PROJECT_ID \
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER \
NEXT_PUBLIC_FIREBASE_APP_ID \
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID \
NEXT_PUBLIC_FIREBASE_MESSAGING_VAPID_KEY \
FIREBASE_PRIVATE_KEY \
FIREBASE_CLIENT_EMAIL \
NEXT_PUBLIC_FIREBASE_ACCESS_KEY

ENV NEXT_PUBLIC_API_MOCKING=$NEXT_PUBLIC_API_MOCKING \ 
NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \ 
NEXT_PUBLIC_SERVER=$NEXT_PUBLIC_SERVER \ 
NEXT_PUBLIC_WS=$NEXT_PUBLIC_WS \ 
NEXT_PUBLIC_CRYPTO_IV_SECRET=$NEXT_PUBLIC_CRYPTO_IV_SECRET \ 
NEXT_PUBLIC_CRYPTO_IV_LENGTH=$NEXT_PUBLIC_CRYPTO_IV_LENGTH \
SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN \
NEXT_PUBLIC_KAKAO_MAP=$NEXT_PUBLIC_KAKAO_MAP \
NEXT_PUBLIC_GA_ACTIVE=$NEXT_PUBLIC_GA_ACTIVE \
NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID \
NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN \
NEXT_PUBLIC_SENTRY_ACTIVE=$NEXT_PUBLIC_SENTRY_ACTIVE \
NEXT_PUBLIC_GOOGLE_VERIFICATION=$NEXT_PUBLIC_GOOGLE_VERIFICATION \
NEXT_PUBLIC_NAVER_VERIFICATION=$NEXT_PUBLIC_NAVER_VERIFICATION \
NEXT_PUBLIC_SSE=$NEXT_PUBLIC_SSE \
NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY \
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID \
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER \
NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID \
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID \
NEXT_PUBLIC_FIREBASE_MESSAGING_VAPID_KEY=$NEXT_PUBLIC_FIREBASE_MESSAGING_VAPID_KEY \
FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY \
FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL \
NEXT_PUBLIC_FIREBASE_ACCESS_KEY=$NEXT_PUBLIC_FIREBASE_ACCESS_KEY

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "start"]
