name: DevBuild

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  build:
    name: docker_build
    if: github.repository == 'KernelSquare/Frontend' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_DEV_TAG }}
          build-args:
            NEXT_PUBLIC_API_MOCKING=${{ secrets.NEXT_PUBLIC_API_MOCKING }}
            NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_DEV_SITE_URL }}
            NEXT_PUBLIC_SERVER=${{ secrets.NEXT_PUBLIC_DEV_SERVER }}
            NEXT_PUBLIC_WS=${{ secrets.NEXT_PUBLIC_DEV_WS }}
            NEXT_PUBLIC_CRYPTO_IV_SECRET=${{ secrets.NEXT_PUBLIC_CRYPTO_IV_SECRET }}
            NEXT_PUBLIC_CRYPTO_IV_LENGTH=${{ secrets.NEXT_PUBLIC_CRYPTO_IV_LENGTH }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_DEV_AUTH_TOKEN }}
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DEV_DSN }}
            NEXT_PUBLIC_SENTRY_ACTIVE=${{ secrets.NEXT_PUBLIC_DEV_SENTRY_ACTIVE }}
            NEXT_PUBLIC_KAKAO_MAP=${{ secrets.NEXT_PUBLIC_KAKAO_MAP }}
            NEXT_PUBLIC_GA_ACTIVE=${{ secrets.NEXT_PUBLIC_DEV_GA_ACTIVE }}
            NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}
  notify:
    needs: build
    if: github.repository == 'KernelSquare/Frontend'
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "Develop Github Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Develop Github Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
